---
title: "Notes"
author: "_sinnabunbun (Marta)_"
date: "9/8/2021"
output: 
  html_document:
    toc: true
    theme: cosmo
---

## Mod 3

"While Linux and Mac OSX both include SSH as part of the base system, Windows does not. As a result the standard Windows distribution of git (Msysgit, referenced above) also includes an SSH client."  
  
  - Unsure what this means, ask for clarification.  
    + is this the same as creating an rsa key?  
  
## Mod 4

### Matrices  

- a matrix is a collection of vectors  
- it can only store one kind of vector at a time (ie. characters vs numerical)  
  + `m <- matrix(data = c(1, 2, 3, 4), nrow = 2, ncol = 2)`  
  + _example of matrix function_
- the matrix is filled by column normally but if you want to manually make it by row (left to right instead of up to down) insert the argument  
  + `m <- matrix(data = c(1, 2, 3, 4), nrow = 2, ncol = 2, byrow=TRUE)`  
- you can also make a matrix by combining two vectors  
  + `v1 <- c(1, 2, 3, 4)`  
  + `v2 <- c(6, 7, 8, 9)`  
  + `m1 <- rbind(v1, v2)`  
  + `m1`  
  + _to combine these two as columns you would use the function `cbind()` instead_  
- _important commands_  
  + `class()' gives you the class of the matrix, `dim()` gives you the amount of rows and columns, `names()` , `rownames()`, `colnames()` will all give you names of the function, however if the names are not defined it will return with _NULL_  
  + `str()` or the structure command will give you details on any data structure.  
  + > This is an incredibly useful function that you will find yourself using over and over again.  -Prof. Schmitt  
- Matrices and vectors are two examples of of a broader term,  _array_  
  + `a <- array(data = 1:90, dim = c(5, 6, 3))`  
  + __example of a three level array with numbers 1-90, `c(5, 6, 3)` i _think_ stands for 5 rows, 6 columns, 3 levels__  
- you can find a _subset_ of an array by using brackets, for example if you assign v the values 1-100 (`v<-1:100`) you can select certain values by saying `v[]` ex. `v[1:15]` or manually selecting the ex. `v[c(3, 4, 10, 15)]  
  + similar to using the function `c()` to subset a vector you can substitute other functions  
  + ex. `v[seq(from = 1, to = 100, by = 2)]` outputs the vector in sequential order, increasing by two  
  + __Note! `from=1, to=100` indicates position 1 to position 100 _not_ necessarily numbers 1 to 100__ 

#### Challenge 1  

- `v1<- c("Stately, ", "plump ", "Buck ", "Mulligan ", "came ", "from ", "the ", "stairhead, ", "bearing ", "a ", "bowl ", "of ", "lather ", "on ", "which ", "a ", "mirror ", "and ", "a ", "razor ", "lay ", "crossed.")`  
- `v1`  
  + _don't forget commas to separate objects_  
  + prof recommends `str_split()` but I don't think I have that properly installed?? help on installing R packages maybe  
- `v1[seq(from = 1, to = 21, by = 3)]`  

#### Challenge 2

- `m <- matrix(data = 1:80, nrow = 8, ncol = 10, byrow = FALSE)`  
- `m`  
- `x <- m[4, 5]`  
  + order is row by column so that value is equal to 36   
- `x<-c(m[, 2], m[, 3], m[,6])`  
  + gives the elements from columns 2, 3, and 6
  + _unsure if this is suppose to be segmented?_  
- `x<-c(m[6,], m[8,])`  
  + assigns variable x the elements from rows 6 and 8  
- `x<-c(m[2, 2]:m[6, 9])`  
  + assigns the elements from (row 2, column 2) to (row 6, column 9) to the variable x  

#### Challenge 3  

- Construct a 4-dimensional, 400 element array (5 x 5 x 4 x 4) named a consisting of the numbers 400 to 1 (i.e., a descending series)  
  + `m<-array(c(400:1), dim = c(5, 5, 4, 4))`  
  + i am __unsure__ how he dimension is manipulated by the 5 x 5 x 4 x 4 elements?? but it does work lol  
- `a[1, 1, 1, 2]`  
  + `[1] 300'  
- `a[2, 3, 2, ]`  
  + `[1] 364 264 164 64  
- `a[1:5, 1:5, 3, 3]`  
  + `[,1] [,2] [,3] [,4] [,5]
[1,]  150  145  140  135  130
[2,]  149  144  139  134  129
[3,]  148  143  138  133  128
[4,]  147  142  137  132  127
[5,]  146  141  136  131  126`  

### Overwriting  

- `m[7, 1] <- 564`  
  + changes element at (7,1) to 564  
- `m[, 8] <- 2`  
  + changes column 8 to all '2' in the elements  
- `m[2:5, 4:8] <- c(20, 19, 18, 17)`  
  + changes the elements in columns 4:8 to change to numbers 20, 19, 18, 17 for rows 2:5  
- `m[2:5, 4:8] <- 1`  
  + changes the elements in columns 4:8 to change to number 1 for rows 2:5  
- `m[2:5, 4:8] <- matrix(data = c(20:1), nrow = 4, ncol = 5, byrow = TRUE)`  
  + ?  
- `m[, 8] <- c("a", "b")`  
  + ?  
-
